# Generated by Django 5.2 on 2025-05-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'CompanyStatus',
            },
        ),
        migrations.CreateModel(
            name='FinanceManagementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'FinanceManagementPeriod',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Industry',
            },
        ),
        migrations.CreateModel(
            name='Commendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('government_departments', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_commendation', models.CharField(blank=True, max_length=1000, null=True)),
                ('target', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'Commendation',
            },
        ),
        migrations.CreateModel(
            name='ChildcareCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maternity_leave_acquisition_num', models.IntegerField(blank=True, null=True)),
                ('number_of_maternity_leave', models.IntegerField(blank=True, null=True)),
                ('number_of_paternity_leave', models.IntegerField(blank=True, null=True)),
                ('paternity_leave_acquisition_num', models.IntegerField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'ChildcareCompatibility',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('government_departments', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_approval', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=255, null=True)),
                ('enterprise_scale', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'Certification',
            },
        ),
        migrations.CreateModel(
            name='CompanyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('close_date', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='companyapp.company')),
            ],
            options={
                'db_table': 'CompanyClosure',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_position', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companyapp.company')),
            ],
            options={
                'db_table': 'CompanyContact',
            },
        ),
        migrations.CreateModel(
            name='CompanyDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_year', models.IntegerField(blank=True, null=True)),
                ('date_of_establishment', models.CharField(blank=True, max_length=255, null=True)),
                ('update_date', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_dates', to='companyapp.company')),
            ],
            options={
                'db_table': 'CompanyDates',
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_summary', models.TextField(blank=True, null=True)),
                ('capital_stock', models.BigIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summaries', to='companyapp.company')),
            ],
            options={
                'db_table': 'CompanyFinancialSummary',
            },
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companyapp.company')),
            ],
            options={
                'db_table': 'CompanyLocation',
            },
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('kana', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='companyapp.company')),
            ],
            options={
                'db_table': 'CompanyName',
            },
        ),
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.IntegerField(blank=True, null=True)),
                ('company_size_male', models.IntegerField(blank=True, null=True)),
                ('company_size_female', models.IntegerField(blank=True, null=True)),
                ('qualification_grade', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='companyapp.company')),
            ],
            options={
                'db_table': 'CompanySize',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_status', to='companyapp.companystatus'),
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_standards', models.CharField(blank=True, max_length=255, null=True)),
                ('fiscal_year_cover_page', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'Finance',
            },
        ),
        migrations.CreateModel(
            name='FinanceMajorShareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_major_shareholders', models.CharField(blank=True, max_length=255, null=True)),
                ('shareholding_ratio', models.FloatField(blank=True, null=True)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.finance')),
            ],
            options={
                'db_table': 'FinanceMajorShareholder',
            },
        ),
        migrations.CreateModel(
            name='FinanceMiAssetMetrics',
            fields=[
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='companyapp.financemanagementperiod')),
                ('net_assets_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('net_assets_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('total_assets_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('total_assets_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'FinanceMiAssetMetrics',
            },
        ),
        migrations.CreateModel(
            name='FinanceMiCapitalMetrics',
            fields=[
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='companyapp.financemanagementperiod')),
                ('capital_stock_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('capital_stock_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'FinanceMiCapitalMetrics',
            },
        ),
        migrations.CreateModel(
            name='FinanceMiEmployeeMetrics',
            fields=[
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='companyapp.financemanagementperiod')),
                ('number_of_employees', models.BigIntegerField(blank=True, null=True)),
                ('number_of_employees_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'FinanceMiEmployeeMetrics',
            },
        ),
        migrations.CreateModel(
            name='FinanceMiIncomeMetrics',
            fields=[
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='companyapp.financemanagementperiod')),
                ('net_income_loss_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('net_income_loss_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('ordinary_income_loss_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('ordinary_income_loss_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('ordinary_income_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('ordinary_income_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'FinanceMiIncomeMetrics',
            },
        ),
        migrations.CreateModel(
            name='FinanceMiRevenueMetrics',
            fields=[
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='companyapp.financemanagementperiod')),
                ('gross_operating_revenue_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('gross_operating_revenue_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('net_sales_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('net_sales_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('net_premiums_written_summary_of_business_results_ins', models.BigIntegerField(blank=True, null=True)),
                ('net_premiums_written_summary_of_business_results_ins_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_revenue1_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('operating_revenue1_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_revenue2_summary_of_business_results', models.BigIntegerField(blank=True, null=True)),
                ('operating_revenue2_summary_of_business_results_unit_ref', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'FinanceMiRevenueMetrics',
            },
        ),
        migrations.AddField(
            model_name='financemanagementperiod',
            name='finance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.finance'),
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.industry')),
            ],
            options={
                'db_table': 'CompanyIndustry',
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('application_number', models.CharField(blank=True, max_length=500, null=True)),
                ('application_date', models.CharField(blank=True, max_length=255, null=True)),
                ('patent_type', models.CharField(blank=True, max_length=255, null=True)),
                ('code_value', models.CharField(blank=True, max_length=255, null=True)),
                ('code_name', models.CharField(blank=True, max_length=255, null=True)),
                ('japanese_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'Patent',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_departments', models.CharField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('date_of_order', models.DateTimeField(blank=True, null=True)),
                ('joint_signatures', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'Procurement',
            },
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_departments', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('date_of_approval', models.TextField(blank=True, null=True)),
                ('subsidy_resource', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('target', models.TextField(blank=True, null=True)),
                ('joint_signatures', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'Subsidy',
            },
        ),
        migrations.CreateModel(
            name='WomenActivityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female_share_of_manager', models.IntegerField(blank=True, null=True)),
                ('female_share_of_officers', models.IntegerField(blank=True, null=True)),
                ('female_workers_proportion', models.FloatField(blank=True, null=True)),
                ('female_workers_proportion_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gender_total_of_manager', models.IntegerField(blank=True, null=True)),
                ('gender_total_of_officers', models.IntegerField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'WomenActivityInfo',
            },
        ),
        migrations.CreateModel(
            name='WorkplaceBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_age', models.FloatField(blank=True, null=True)),
                ('average_continuous_service_years', models.FloatField(blank=True, null=True)),
                ('average_continuous_service_years_type', models.CharField(blank=True, max_length=255, null=True)),
                ('month_average_predetermined_overtime_hours', models.FloatField(blank=True, null=True)),
                ('average_continuous_service_years_female', models.FloatField(blank=True, null=True)),
                ('average_continuous_service_years_male', models.FloatField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'db_table': 'WorkplaceBaseInfo',
            },
        ),
    ]
